services:
  nginx:
    image: nginx:alpine
    container_name: django-tailwindcss-auth-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - staticfiles:/staticfiles
      - ./media:/media
    depends_on:
      - web
    networks:
      - django-tailwindcss-auth-network
  web:
    build: .
    container_name: django-tailwindcss-auth-web
    command: sh -c "uv run python manage.py migrate --noinput && uv run python manage.py collectstatic --noinput && uv run gunicorn config.asgi:application -k uvicorn_worker.UvicornWorker --bind 0.0.0.0:8000"
    volumes:
      - staticfiles:/app/staticfiles
      - ./media:/app/media
    env_file:
      - .env
    networks:
      - django-tailwindcss-auth-network
  postgres:
    image: postgres:17
    container_name: django-tailwindcss-auth-postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - django-tailwindcss-auth-network
networks:
  django-tailwindcss-auth-network:
    driver: bridge
volumes:
  staticfiles:
  postgres_data: