# Generated by Django 5.1.1 on 2025-10-07 00:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="タイトル")),
                ("description", models.TextField(blank=True, verbose_name="説明")),
                (
                    "file_type",
                    models.CharField(
                        choices=[("audio", "音声"), ("video", "動画")],
                        max_length=10,
                        verbose_name="ファイル種別",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="media_files/%Y/%m/%d/", verbose_name="ファイル"
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        verbose_name="ファイルサイズ（バイト）"
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        blank=True, null=True, verbose_name="再生時間"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "メディアファイル",
                "verbose_name_plural": "メディアファイル",
                "ordering": ["-created_at"],
            },
        ),
    ]
